sudo: required
services:
  - docker

before_install:
  - docker pull buddyvolly/opensartoolkit:latest

script:
  - docker run buddyvolly/opensartoolkit:latest /bin/sh -c "export TRAVIS=$TRAVIS; cd OpenSarToolkit; pip uninstall -y ost; git fetch; git checkout $TRAVIS_BRANCH; git pull; python setup.py install; pytest ost tests/;"
